---
- name: Installing Bandito - A monitoring system that utilises Nagios to monitor the TOR network in its entirety. 
  hosts: all
  become: true
  tasks:
        - debug:
                msg: Remember to setup variables in var.yml or you'll get no where...

        - include_vars: vars.yml
  roles:
        - common

